### ISSUE TITLE
Incompatibility with Snow! Real Magic! mod

### ISSUE THREAD

**Issue by Snownee** [LudoCrypt/The-Corners#10]
Don't know why but it seems to be incompatible with my mod [Snow! Real Magic!](https://github.com/Snownee/SnowRealMagic).

All the snow-covered blocks become invisible:

![image](https://user-images.githubusercontent.com/16059084/150460695-86cff23b-375b-4145-9c08-05e65429034e.png)

**Comment by LudoCrypt** [comment]
Hey, i was gonna have a similar effect in one of my dimensions! I might tell people to use this mod for it. Anyways, thats probably because we're both changing the models. In my code, i remove every single quad that has a texture that is in the 'sky/' directory, and render that. Id have to look into how your mod does it.

**Comment by LudoCrypt** [comment]
I think its fixed?
